### ISSUE TITLE
code 수정 제안

### ISSUE THREAD

**Issue by modooJH** [yesj1234/farmers_journal#2]
승준님 현재 진행된 코드에 대해 의견드립니다.  

### Journal.fromFirestore

model은 고유하게 dart로만 구성합니다. DocumentSnapshot은 firestore sdk로부터 온 것으로 종속성이 생기면 안됩니다.  통상 snapshot은 service에 두는게 좋습니다.  승준님이 작성하신 코드상으로 prviders에 두는게 좋습니다. 

## providers.dart

이름을 firestore_service.dart로 수정하는게 더 좋겠습니다.  flutter에서 provider는 주로 객체를 제공하는 역할로 많이 쓰여서 naming이 헷갈릴 수 있어요.  혹시라도 riverpod에서 이런 형태로 사용하는게 일반적이라면 이대로 이름 유지해도 괜찮습니다. 
( 저는 riverpod을 잘 모릅니다. )
## avatar_profile.dart
storage에 access 하는 코드는 다른 파일로 분리하는게 좋겠습니다.   
firestore에 access 하는 코드가 providers.dart로 분리되어 있듯이 일관성 있게 만들면 더 좋겠습니다.   
보통 storage_service.dart 형태로 많이 사용합니다. 

initState에서 setState를 호출하는게 좋은 방식은 아닙니다.  현재 비동기라서 문제없을지 모르지만, 권장되는 모양은 아닙니다. 꼭 써야 할 경우 addPostFrameCallback을 활용하세요. 

NetworkImage를 이용할 때는 error일 경우 어떻게 처리할지 꼭 생각해야 합니다.  CircleAvatar는 errorBuilder를 제공하지 않아서 이 부분 처리를 조금 고민하셔야겠지만, error상황을 반드시 처리해줘야 합니다. 

주로 NetworkImage가 error라면 AssetImage를 이용해 default Image를 출력하는 방식으로 접근합니다.

## 총평

승준 님이 개발하는 방식이 기능단위로 이루어져 있습니다.  
flutter에 익숙하지 않은 입장에서 이런 접근보다는 화면개발을 완료하고, model 구현하고,  기능 구현하는 순서로 하는게 유리합니다.  
물론 승준 님의 개발 방식을 유지하셔도 됩니다. 아무 문제 없습니다.  혹시나 별다른 의도 없이 손이 가는 대로 선택한 방법이실까봐 의견 드려봅니다.  

개발 진행하시면서 제 의견이 필요하시면 언제든 문의주세요. 

화이팅입니다.

**Comment by yesj1234** [comment]
피드백 감사합니다. 
최대한 반영하도록 노력해보겠습니다!
